"""
Django settings for midwives_elearning project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a+j-wcwo#l&n6-cnyvr1fx1xv5d+sb368&_4ng9^z43nxottif'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['fcmc.muberarugo.org', '127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'api',
    'rest_framework.authtoken',
    'drf_yasg',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.common.BrokenLinkEmailsMiddleware', 
]

ROOT_URLCONF = 'midwives_elearning.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'midwives_elearning.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'database/database.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# Directory where Django will look for additional static files, aside from each app's 'static' directory
STATICFILES_DIRS = (
     os.path.join(BASE_DIR, 'assets'),  # Change this to a different folder from STATIC_ROOT
    #  os.path.join(BASE_DIR, 'static'),
)

# URL to use when referring to static files located in STATIC_ROOT
STATIC_URL = '/static/'

# Directory where the static files will be collected to
STATIC_ROOT = '/var/www/midwives_elearning/static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Good for production

# Media files
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'  # Make sure to also set MEDIA_URL

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'api.HealthProviderUser'

JAZZMIN_SETTINGS = {
    "site_title": "MUBERAGURUGO ADMIN",
    "site_header": "MUBERAGURUGO",
    "site_brand": "MUBERAGURUGO",
    "site_logo": 'assets/logo.png',
    "login_logo": 'assets/logo.png',
    "copyright": "MUBERAGURUGO Ltd",
    
    # Optional settings
    "site_icon": "assets/logo.png",  # Icon shown in the admin
    "welcome_sign": "Welcome to the MUBERAGURUGO Admin",  # Welcome message for the admin dashboard
    "show_sidebar": True,  # Show the sidebar on the admin page
    "navigation_expanded": True,  # Expand the navigation bar by default
    "icons": {
        "auth": "fas fa-user",  # Example of adding icons to the 'auth' app
        "app": "fas fa-cogs",  # Custom icon for your app
        # Add more icons for other models or apps as needed
    },
    "custom_css": "assets/custom.css",  # Path to custom CSS file for further styling
    "custom_js": "assets/custom.js",  # Path to custom JavaScript file for interactivity
    "collapse_menu": True,  # Collapse the sidebar by default
    "show_ui_builder": False,  # Enable or disable the UI builder
}

