# Generated by Django 5.0.3 on 2024-10-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_question_course_certificate_enrollment_exam_lesson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
