# Generated by Django 5.0.3 on 2024-10-11 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_lesson_pdf_file'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='healthprovideruser',
            managers=[
            ],
        ),
    ]
