# Generated by Django 5.0.3 on 2024-10-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_course_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='completed_quizzes',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='progress',
            name='completed_lessons',
            field=models.JSONField(default=list),
        ),
    ]
