# Generated by Django 5.1.2 on 2024-10-17 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_examsubmission_quizsubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizsubmission',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizsubmission',
            name='user',
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question')),
                ('selected_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'question')},
            },
        ),
        migrations.DeleteModel(
            name='ExamSubmission',
        ),
        migrations.DeleteModel(
            name='QuizSubmission',
        ),
    ]
