# Generated by Django 5.1.2 on 2024-10-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_skill_course_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprovideruser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
