# Generated by Django 5.1.2 on 2024-11-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_healthprovideruser_telephone_onetimepassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthprovideruser',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
