# Generated by Django 5.1.2 on 2024-11-02 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_examquestion_examanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='certificate_file',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='date_issued',
        ),
        migrations.AddField(
            model_name='certificate',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.exam'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
