# Generated by Django 5.1.2 on 2024-11-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_certificate_issued_date_alter_certificate_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='completed_lessons',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='completed_quizzes',
        ),
        migrations.AddField(
            model_name='progress',
            name='completed_lessons',
            field=models.ManyToManyField(blank=True, related_name='progressed_lessons', to='api.lesson'),
        ),
        migrations.AddField(
            model_name='progress',
            name='completed_quizzes',
            field=models.ManyToManyField(blank=True, related_name='progressed_quizzes', to='api.quiz'),
        ),
    ]
