# Generated by Django 5.1.2 on 2024-11-07 09:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_userexamprogress_userlessonprogress_userquizprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='users',
            field=models.ManyToManyField(through='api.UserLessonProgress', to=settings.AUTH_USER_MODEL),
        ),
    ]
