# Generated by Django 5.1.2 on 2024-12-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_emergency_emergencyfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='completion_status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=50),
        ),
    ]
