# Generated by Django 5.1.2 on 2024-12-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_enrollment_completion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='completed_exams',
            field=models.ManyToManyField(blank=True, related_name='progressed_exams', to='api.exam'),
        ),
    ]
